### ISSUE TITLE
ViewPager with Reviews

### ISSUE THREAD

**Issue by Abazzi** [Abazzi/AndroidProject#26]

**Comment by mgellakkis** [comment]
Hi guys,
I am not sure what I am suppose to do here and no comments on git hub, also cart still showing in the navigation drawer and the premade page not aligned well yet so ... Can you elaborate on that as well

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mgellakkis** [comment]
Adam, pull request 30 is before 29 please

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
